### PR TITLE
Update init.sqf in PvP Template limiting functionality of MCC for players

### PR DESCRIPTION
**Pull request by xand3rr**
Edit to MCC_grass_array so people cannot ''cheat'' by not having grass.

### CODE REVIEW

**Comment by freghar** [comment]
@xand3rr Any update on the testing? Can this be merged?

**Comment by xand3rr** [comment]
I haven't tested it with multiple people, is anyone willing to test this one with multiple people? 
(the mission is already on the server, PvP - Multiple Choise on Bukovina)
It adds multiple ''medium'' options, because MCC saves the index, thus helping the compatibility with missions which dont have this. (array length issues)

**Comment by freghar** [comment]
I'm not sure why it needs testing with multiple people, but I tried it on the CNTO server (the mission you mentioned) and seems to work as expected. :)

**Comment by xand3rr** [comment]
Awesome, should we push this one to the PvP template?

**Comment by freghar** [comment]
We're currently in the process of making a new generic (Coop?) template, I would suggest we wait for it to be available in the repository, so we can fork PvP template off it and apply this change, instead of applying it to r0b9 and then porting over.

@CNTODachi Am I correct? How should we handle this?

**Comment by CNTODachi** [comment]
> We're currently in the process of making a new generic (Coop?) template, I would suggest we wait for it to be available in the repository, so we can fork PvP template off it and apply this change, instead of applying it to r0b9 and then porting over.

Yeah I think your exactly right we wait for the r0b10 Final Template to hit the GitHub and then implement this in the r0b10 PvP Template.

**Pull request merged**
