### PR TITLE
Update init.sqf

### PR DESCRIPTION
**Pull request by TRyujin**
Bull contacted me on Tuesday regarding the current version of ACRE using different values. He recommended we set it to 0.05 in order to avoid loosing radio comms. You could notice this with 343 radios on this Friday's mission, even at ~50m distance if there was a building or foliage between, comms would come in more scrambled than expected.

### CODE REVIEW

**Comment by BullHorn7** [comment]
That's a good value to test for a couple of ops. It might still be too harsh and we might have to completely disable terrain loss, unless you guys think a tiny bit of radio-realism where comms break down is a good idea.

**Comment by milivojm** [comment]
0.2 is not enough? Hello Kitty radio can transmit on 300m and military radio is unable according to acre team. 

I would ditch acre. Nice idea but issue list like Windows ME.

**Comment by BullHorn7** [comment]
AN-PRC 343 uses 2.4GHz frequency with output power of 50mW. It's basically a glorified WiFi router with  a speaker and microphone. It's designed for intra-fireteam close-range communication and thanks to the weak signal has a very low probability of interception.

Future ACRE2 versions will have more radios designed for slightly longer range communications (but shorter than VHF).

Why ditch it if you can disable or tweak the feature with a single command?

**Comment by milivojm** [comment]
It's still badly implemented. 

http://www.milspec.ca/radspec/prc-343.html

You've seen yesterday, we were in the open and definitely less than 500m away (according to the spec, open terrain range). And were having distortions. I don't think we should disable the signal loss, that is one of the reasons why ACRE is popular in the first place.

**Comment by BullHorn7** [comment]
That is inaccurate. 

From your link:
Features:
Up to 500m Range
Specifications:
Range: 500 meters (Rural Terrain) transmission through up to three floors (Urban Terrain)

Most of the issues we faced were around buildings.

Your other misconception is that ACRE is popular because of its realistic radios, however if that was the case, then we would've not been setting terrain loss to 0.2 this whole time. ACRE is popular because it has superior direct speech behavior compared to the competition which uses TeamSpeak's built-in direct speech simulation feature.

Here is a test we held while we were contemplating which communication system we're going to use: https://www.youtube.com/watch?v=xmpRFEvEq4c

Speaking of direct speech, starting with build .887 (and currently .889 that looks very stable and might be released as stable), they have reworked how direct speech occlusion works and it actually sounds good. I'll try to get a video of that up once I get someone to test with.

**Comment by milivojm** [comment]
Hahaha, I loved the video. Listen Bull, without a doubt a full working ACRE 2 >>> TFR. But TFR works good for little it does. ACRE 2 sometimes works well. That's the problem.

**Comment by freghar** [comment]
We still an ACRE2 fix in the meantime, is everyone okay with the 0.2 -> 0.05 change, whatever it means? I just came from a miniop where we couldn't hear each other on the radio 150m away.

We could hot-fix it into r0b11.

**Comment by TRyujin** [comment]
Yes let's implement this hotfix. We don't have a lot missions so there won't be a lot of updating, and those that will, it will be simple two-character change.

I don't know which template is proper one in !Stable folder. There is CNTO-Template.Altis and CNTO-r0b10-Coop-Template.Altis.

**Comment by freghar** [comment]
> I don't know which template is proper one in !Stable folder. There is CNTO-Template.Altis and CNTO-r0b10-Coop-Template.Altis.

If I understood Dachi correctly, CNTO-r0b10 is the final release we did, however as the current system in git is so FUBAR, please don't send this change as a pull request, it doesn't work this way.

**Comment by CNTODachi** [comment]
I have added the hot fix to all templates so Coop, PvP and Training Grounds. Also I tweaked certain things listed below.

I noticed that all loadout had flashlights and IR Strobes why all the time so I added them to items that can be applied to all, like compass and map you just take the \\ out to activate them for night missions instead of adding to every single unit type and as they already fit this is not a problem.

I also LOP proofed all the Templates by removing any LOP assets and so they can all run without if we want to conduct testing to see if LOP is causing issues.

Regards,
Dachi

P.S both files in the stable area are the same. Coop-Template is there so no matter what the version of the template when we overwrite the core folders with a new template version we can all see the cangelog that git provides. In order to compare differences and help debug potential problems with new templates.

**Comment by milivojm** [comment]
Did anyone report this problem to acre team?

**Comment by BullHorn7** [comment]
It's not a problem, it was an intended design change. Radios IRL are often unreliable pieces of shit and the 343 is the king. Soldiers used to prefer to shout rather than try to use it, which is why the USMC and US Army no longer use it.

ACRE2 devs are currently waiting for a Harris 7800 SPR 3D model to be finished and added. Other than that all the code for it already exists and it's purpose is to be an alternative for the 343 where slightly less shitty comms are desired (unless of course shitty comms is part of your gameplay, for example if you play as guerilla or whatever). 

For now the terrain loss function allows you to change this. If you want the TFAR arcade experience, you can just set the value to 0 (or disable Terrain Loss in the editor Module) and then only distance will affect signal propagation.

**Comment by CNTODachi** [comment]
Ok so if it is design intended then let's roll back and keep .811 for as long as possible because although I like that they are sticking to real life when in a game this shouldn't really be replicated as it wastes time sort out comms issues when we should be planning and getting the mission rolling.

**Comment by TRyujin** [comment]
Before we get rolling backwards, we'll first test .889 and if it works (doesn't show .871 issues) we'll update to it.

**Comment by Abuk007** [comment]
Agreed. No point on taking a step back to go down the same road later. If .889 is OK then we'll simply update. If the issue persists then we go back to .811 and stay there until we find a major upgrade that's stable and tested before changing versions.


Wysłane z telefonu Samsung

<div>-------- Oryginalna wiadomość --------</div><div>Od: TRyujin <notifications@github.com> </div><div>Data:03.04.2016  12:45  (GMT+01:00) </div><div>Do: CntoDev/cnto-mmt-repo <cnto-mmt-repo@noreply.github.com> </div><div>DW:  </div><div>Temat: Re: [CntoDev/cnto-mmt-repo] Update init.sqf (#93) </div><div>
</div>Before we get rolling backwards, we'll first test .889 and if it works (doesn't show .871 issues) we'll update to it.

**Comment by CNTODachi** [comment]
Me and Ryujin,

Tested .889 and the problem did not persist but I want to test one more time before I say it is good to go. I can test later today if people are around.

**Comment by BullHorn7** [comment]
Sounds good. 

Offtopic but if you want, try removing the direct speech occlusion command from the init.sqf during .889 test and try talking around and inside buildings, they have completely reworked that feature and it should now be pleasant and enjoyable.

**Pull request closed without merging**
