### PR TITLE
Update mission.sqm

### PR DESCRIPTION
**Pull request by xand3rr**
Adds all units made in eden to the editableObjects list, so Zeus etc can play with them

### CODE REVIEW

**Comment by freghar** [comment]
@xand3rr Does this work with the MCC curator instance, reliably? Our MCC GM unit doesn't have a Curator module linked in the template, it presumably relies on MCC taking care of that. The MCC curator instance runs from the addon's init.sqf on the server only and declares it as publicVariable, wouldn't that create a race against the clients running init lines of units, potentially calling the Ares function before the MCC curator instance is initialized?

Shouldn't this be executed on the server only, with `waitUntil` the curator publicVariable exists, as the mission init.sqf seems to run in an unscheduled environment?

**Comment by Abuk007** [comment]
There's an issue with that and MCC I've spotted. Because it adds everything to zeus that means if you save the mission with MCC to load it later it will double the spawns thus causing massive explosions and collisions across entire map where objects where placed.

(MCC saves all objects avail in Zeus, thus when you "load" with MCC you spawn things on top of existing editor things - like buildings, vehicles etc.)

It's safe to place things in editor, make something in MCC and save it. Then after using MCC load function use Ares to add all objects to zeus.

**Comment by CNTODachi** [comment]
If Ares gives us the ability to add objects to Zeus and it works already, is there a need for this?

Just thinking out loud because if there will be problems implementing as Freghar has suggested there might be then maybe we should hold off until we have time to test and see advantages of implementing.

**Comment by xand3rr** [comment]
You probably can do this with Ares, yes.
I only added this so that GM's don't have to do the extra effort.

If it causes problems ( I don't see this causing double spawns, it only 'marks' units as editable, it doesn't add any units on its own.)

This is a local function, and only applies to the current MCC.
So if a new MCC logins, he would have to do the same thing again.

Do note this code can be optimized with a `if(local this) then {..code..}`

**Comment by freghar** [comment]
> please give the exact data for this (im curious :) )

The problem is that MCC saves all units that are "marked as editable" (under control) of the current Zeus. Imagine:

 1. some base units are placed in the editor
 2. you load the mission, spawn few more units in, save them via MCC
 3. quit everything

On mission day, you

 1. load the base mission, as usual
 2. load MCC

All units will be duplicated, because you saved all (even editor-placed) units via MCC previously, not just the few newly added ones.

> This is a local function, and only applies to the current MCC.
> So if a new MCC logins, he would have to do the same thing again.

Not really, AFAIK what matters is which units are added to the Curator instance, not to the player. The instance becomes local as soon as you (or MCC upon Login) do `assignCurator`, but it should retain its units between assigned players.

> Do note this code can be optimized with a `if(local this) then {..code..}`

Then it would be the same as `if (isServer)`, because `MCC_curator` starts local to server, until somebody logs in via the MCC UI.

**Comment by xand3rr** [comment]
Ok, it's all about your workflow I guess then, I personally don't save/load MCC missions, I just make them in the editor.
In your workflow the Ares module itself could be used on the mission day, indeed !

Talking about locality, I just saw the page on the BI Wiki, and indeed its a server command ( https://community.bistudio.com/wiki/addCuratorEditableObjects ) missed that, sorry !

I think because of the different workflows of people, this request should be put down.

**Comment by freghar** [comment]
> In your workflow the Ares module itself could be used on the mission day, indeed !

Not really, Ares SQF-based load doesn't disable simulation while it's loading, causing fireworks and mayhem as it does so, especially for vehicles (with crew inside) or static weapons (mortars, HMGs, ..). It's essentially unusable for anything except sandbags, that's why people stick with MCC save/load for cases where it makes sense, ie. repeatedly loading AI setup within a compound during a training scenario, to have multiple re-tries on clearing it.

> I think because of the different workflows of people, this request should be put down.

Okay, I'm closing this. If we decide we want something like this in the future, let's do it in init.sqf properly and not "hacked" into some unit's init line (as `MCC_curator` isn't bound to a unit).

**Pull request closed without merging**
